import { useEffect } from "react";
import { createPortal } from "react-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTriangleExclamation, faXmark } from "@fortawesome/free-solid-svg-icons";
export default function MasterConfirmModal({ isOpen, title, message, confirmLabel = "تأكيد", cancelLabel = "إلغاء", isDanger = false, isLoading = false, onConfirm, onCancel }) {
 useEffect(() => { if (!isOpen) return undefined; const handleKey = (event) => { if (event.key === "Escape" && !isLoading) onCancel(); }; document.addEventListener("keydown", handleKey); return () => document.removeEventListener("keydown", handleKey); }, [isOpen, isLoading, onCancel]);
 if (!isOpen) return null;
 return createPortal(<div dir="rtl" className="fixed inset-0 z-[5000] flex items-center justify-center bg-black/65 p-4 backdrop-blur-[2px]" onMouseDown={(event) => { if (event.target === event.currentTarget && !isLoading) onCancel(); }}><section role="alertdialog" aria-modal="true" aria-labelledby="master-confirm-title" className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0c1a2b] p-5 shadow-[0_18px_55px_rgba(0,0,0,0.45)] sm:p-6"><div className="flex items-start justify-between gap-4"><span className={"flex h-11 w-11 shrink-0 items-center justify-center rounded-xl " + (isDanger ? "bg-danger/10 text-danger" : "bg-gold/10 text-gold")}><FontAwesomeIcon icon={faTriangleExclamation}/></span><button type="button" onClick={onCancel} disabled={isLoading} aria-label="إغلاق نافذة التأكيد" className="flex h-9 w-9 items-center justify-center rounded-lg text-white/45 transition hover:bg-white/[0.05] hover:text-white disabled:opacity-40"><FontAwesomeIcon icon={faXmark}/></button></div><h2 id="master-confirm-title" className="mt-5 text-lg font-black text-white">{title}</h2><p className="mt-2 whitespace-pre-line text-sm font-bold leading-7 text-white/55">{message}</p><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-start"><button type="button" onClick={onCancel} disabled={isLoading} className="min-h-11 rounded-xl border border-white/10 px-4 text-sm font-extrabold text-white/60 transition hover:bg-white/[0.04] disabled:opacity-40">{cancelLabel}</button><button type="button" onClick={onConfirm} disabled={isLoading} className={"min-h-11 rounded-xl px-4 text-sm font-extrabold transition disabled:cursor-wait disabled:opacity-50 " + (isDanger ? "bg-danger/15 text-danger hover:bg-danger hover:text-white" : "bg-gold text-midnight hover:bg-gold-light")}>{isLoading ? "جارٍ التنفيذ..." : confirmLabel}</button></div></section></div>, document.body);
}
